### ISSUE TITLE
When login into Gowtopia the GTL apps crash 

### ISSUE THREAD

**Issue by DepriPramana** [ZTzTopia/GTIntercherAndroid#1]
After i test this still need fix when login Growtopia always crash.

**Comment by ZTzTopia** [comment]
> After i test this still need fix when login Growtopia always crash.

Did you build it or download from release page?

**Comment by DepriPramana** [comment]
I used 2 release. one from download and one from build but every login always force closed

**Comment by Nubiza** [comment]
same
