### ISSUE TITLE
Don't use c++_static

### ISSUE THREAD

**Issue by 1337heker** [ZTzTopia/GTIntercherAndroid#3]
https://github.com/ZTzTopia/GTIntercherAndroid/blob/dev/app/src/main/jni/Application.mk#L3

on this sizeof(std::string) is not 8, 
You must use gnustl with android ndk r17c (last one that has it, btw gt uses it for their lib), in case you want to reverse structs and get values of std::string elements.

IDK if there is another way

**Comment by ZTzTopia** [comment]
There is another way without changing the standard library, namely by implementing std::string from gnu source
